# Generated by Django 5.2.8 on 2026-01-12 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereport',
            name='product',
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='client_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='client_representative_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='donor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='location',
            field=models.CharField(help_text='City / Facility / Department', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Review'), ('Completed', 'Completed')], default='Draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_note', models.TextField(blank=True, help_text='Specific note for this equipment', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.servicereport')),
            ],
        ),
    ]
