# Generated by Django 5.2.8 on 2026-01-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_servicereport_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportitem',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial number for this specific item', max_length=255, null=True),
        ),
    ]
