# Generated by Django 5.2.8 on 2026-01-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reportitem_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='client_phone_number',
            field=models.CharField(blank=True, help_text='Contact number for the client', max_length=20, null=True),
        ),
    ]
