# Generated by Django 5.2.8 on 2026-01-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicereport_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='billing_category',
            field=models.CharField(blank=True, help_text='Comma-separated billing categories', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='service_type',
            field=models.CharField(blank=True, help_text='Comma-separated service types', max_length=255, null=True),
        ),
    ]
