# Generated by Django 5.2.8 on 2026-01-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servicereport_billing_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='final_status',
            field=models.CharField(blank=True, help_text='Comma-separated final status outcomes', max_length=255, null=True),
        ),
    ]
