# Generated by Django 5.2.8 on 2026-01-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_servicereport_final_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereport',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='client_representative_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='issue_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='location',
            field=models.CharField(blank=True, help_text='City / Facility / Department', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='service_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='work_performed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
