# Generated by Django 5.2.8 on 2026-01-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_servicereport_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='project_reference',
            field=models.CharField(blank=True, help_text='Project Reference / Contract Number', max_length=100, null=True),
        ),
    ]
