# Generated by Django 5.2.8 on 2026-01-14 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_servicereport_project_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_contact_date', models.DateField(auto_now_add=True)),
                ('availability_start', models.DateField(blank=True, help_text='Start of window user is available', null=True)),
                ('availability_end', models.DateField(blank=True, help_text='End of window user is available', null=True)),
                ('urgency', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Emergency', 'Emergency')], default='Medium', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('facility_name', models.CharField(blank=True, max_length=255, null=True)),
                ('donor', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment_list', models.TextField(help_text='List of names for equipment')),
                ('request_details', models.TextField(blank=True, help_text='Additional relevant details', null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
