# Generated by Django 5.2.8 on 2026-01-14 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_maintenancerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='customer_contact_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
