# Generated by Django 5.2.8 on 2026-01-14 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_maintenancerequest_customer_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Optional contact email', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='equipment_list',
            field=models.TextField(blank=True, help_text='Legacy list of names for equipment', null=True),
        ),
        migrations.CreateModel(
            name='MaintenanceRequestEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(help_text='Type of instrument', max_length=255)),
                ('model_name', models.CharField(help_text='Model of instrument', max_length=255)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='core.maintenancerequest')),
            ],
        ),
    ]
