# Generated by Django 5.2.8 on 2026-01-14 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_maintenancerequest_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='maintenance_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reports', to='core.maintenancerequest'),
        ),
    ]
