# Generated by Django 5.2.8 on 2026-01-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_servicereport_maintenance_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='billing_status',
            field=models.CharField(choices=[('Warranty', 'Under Warranty'), ('Billable', 'Billable'), ('Contract', 'Under Contract'), ('FOC', 'Free of Charge')], default='Billable', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Engineer's estimated pricing", max_digits=12, null=True),
        ),
    ]
