# Generated by Django 5.2.8 on 2026-01-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_maintenancerequest_billing_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='serial_number',
        ),
    ]
