# Generated by Django 5.2.8 on 2026-01-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_savedfilter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['manufacturer', 'model']},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('manufacturer', 'model')},
        ),
    ]
