# Generated by Django 4.2.7 on 2026-01-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_product_options_alter_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='service_type',
            field=models.CharField(blank=True, help_text='Comma-separated service types', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='location',
            field=models.CharField(blank=True, choices=[('Beirut', (('Beirut', 'Beirut'),)), ('Mount Lebanon', (('Baabda', 'Baabda'), ('Matn', 'Matn'), ('Chouf', 'Chouf'), ('Aley', 'Aley'), ('Keserwan', 'Keserwan'), ('Jbeil', 'Jbeil'))), ('North Lebanon', (('Tripoli', 'Tripoli'), ('Zgharta', 'Zgharta'), ('Bsharri', 'Bsharri'), ('Batroun', 'Batroun'), ('Koura', 'Koura'), ('Minieh-Danniyeh', 'Minieh-Danniyeh'))), ('Akkar', (('Akkar', 'Akkar'),)), ('Beqaa', (('Zahle', 'Zahle'), ('Rashaya', 'Rashaya'), ('West Beqaa', 'West Beqaa'))), ('Baalbek-Hermel', (('Baalbek', 'Baalbek'), ('Hermel', 'Hermel'))), ('South Lebanon', (('Sidon', 'Sidon'), ('Jezzine', 'Jezzine'), ('Tyre', 'Tyre'))), ('Nabatieh', (('Nabatieh', 'Nabatieh'), ('Marjeyoun', 'Marjeyoun'), ('Hasbaya', 'Hasbaya'), ('Bint Jbeil', 'Bint Jbeil')))], max_length=100, null=True),
        ),
    ]
