# Generated by Django 4.2.7 on 2026-01-26 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_maintenancerequest_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequestequipment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
        migrations.AlterField(
            model_name='maintenancerequestequipment',
            name='equipment_type',
            field=models.CharField(help_text='Type of instrument (Auto-filled if product is selected)', max_length=255),
        ),
        migrations.AlterField(
            model_name='maintenancerequestequipment',
            name='model_name',
            field=models.CharField(help_text='Model of instrument (Auto-filled if product is selected)', max_length=255),
        ),
    ]
