# Generated by Django 6.0.1 on 2026-01-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_maintenancerequestequipment_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['product', 'serial_number'], 'verbose_name_plural': 'Equipment Registry'},
        ),
        migrations.RemoveField(
            model_name='maintenancerequestequipment',
            name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='maintenancerequestequipment',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='maintenancerequestequipment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reportitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reportitem',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='availability_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='availability_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='request_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='service_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='equipment_note',
            field=models.TextField(blank=True, help_text='Specific note for this equipment during this service', null=True),
        ),
        migrations.AlterField(
            model_name='savedfilter',
            name='filter_params',
            field=models.JSONField(),
        ),
    ]
