# Generated by Django 6.0.1 on 2026-01-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='warranty_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='warranty_duration_years',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 Year'), (2, '2 Years'), (3, '3 Years'), (4, '4 Years'), (5, '5 Years')], null=True, verbose_name='Warranty Duration'),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='warranty_start_on_submission',
            field=models.BooleanField(default=False, help_text='If checked, linked equipment warranty will be updated.', verbose_name='Warranty starts the day the report is submitted'),
        ),
    ]
