# Generated by Django 6.0.1 on 2026-02-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_maintenancerequest_pricing_set_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='report_thumbnails/'),
        ),
    ]
