# Generated by Django 6.0.1 on 2026-02-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_reportimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='urgency',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Emergency', 'Emergency')], db_index=True, default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='follow_up_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Review'), ('Completed', 'Completed')], db_index=True, default='Draft', max_length=20),
        ),
    ]
