# Generated by Django 6.0.1 on 2026-02-03 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_maintenancerequest_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Sales', 'Sales'), ('Procurement', 'Procurement'), ('Management', 'Management')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('duration', models.CharField(help_text='e.g., 2 hours, Full day', max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Edit Requested', 'Edit Requested')], db_index=True, default='Pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.driver')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
