# Generated by Django 6.0.1 on 2026-02-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_driver_driverrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrequest',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='vehicle_type',
            field=models.CharField(choices=[('Truck', 'Truck'), ('Car', 'Car'), ('Moto', 'Moto')], default='Car', max_length=20),
        ),
        migrations.AlterField(
            model_name='driverrequest',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g., 2 hours, Full day', max_length=100, null=True),
        ),
    ]
