# Generated by Django 6.0.1 on 2026-02-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_driverrequest_end_time_driverrequest_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrequest',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='End User (Client)'),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driverrequest',
            name='location',
            field=models.CharField(choices=[('Beirut', [('Beirut', 'Beirut')]), ('Mount Lebanon', [('Baabda', 'Baabda'), ('Matn', 'Matn'), ('Chouf', 'Chouf'), ('Aley', 'Aley'), ('Keserwan', 'Keserwan'), ('Jbeil', 'Jbeil')]), ('North Lebanon', [('Tripoli', 'Tripoli'), ('Zgharta', 'Zgharta'), ('Bsharri', 'Bsharri'), ('Batroun', 'Batroun'), ('Koura', 'Koura'), ('Minieh-Danniyeh', 'Minieh-Danniyeh')]), ('Akkar', [('Akkar', 'Akkar')]), ('Beqaa', [('Zahle', 'Zahle'), ('Rashaya', 'Rashaya'), ('West Beqaa', 'West Beqaa')]), ('Baalbek-Hermel', [('Baalbek', 'Baalbek'), ('Hermel', 'Hermel')]), ('South Lebanon', [('Sidon', 'Sidon'), ('Jezzine', 'Jezzine'), ('Tyre', 'Tyre')]), ('Nabatieh', [('Nabatieh', 'Nabatieh'), ('Marjeyoun', 'Marjeyoun'), ('Hasbaya', 'Hasbaya'), ('Bint Jbeil', 'Bint Jbeil')])], max_length=100),
        ),
    ]
