# Generated by Django 6.0.1 on 2026-02-03 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_driverrequest_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrequest',
            name='maintenance_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_trips', to='core.maintenancerequest'),
        ),
    ]
