# Generated by Django 6.0.1 on 2026-02-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_driverrequest_maintenance_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_info',
            field=models.CharField(blank=True, default='Class A CDL Holder', help_text='e.g., Class A CDL Holder', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/'),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='estimated_distance',
            field=models.CharField(blank=True, help_text='e.g., 30 km', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='origin',
            field=models.CharField(choices=[('Beirut', [('Beirut', 'Beirut')]), ('Mount Lebanon', [('Baabda', 'Baabda'), ('Matn', 'Matn'), ('Chouf', 'Chouf'), ('Aley', 'Aley'), ('Keserwan', 'Keserwan'), ('Jbeil', 'Jbeil')]), ('North Lebanon', [('Tripoli', 'Tripoli'), ('Zgharta', 'Zgharta'), ('Bsharri', 'Bsharri'), ('Batroun', 'Batroun'), ('Koura', 'Koura'), ('Minieh-Danniyeh', 'Minieh-Danniyeh')]), ('Akkar', [('Akkar', 'Akkar')]), ('Beqaa', [('Zahle', 'Zahle'), ('Rashaya', 'Rashaya'), ('West Beqaa', 'West Beqaa')]), ('Baalbek-Hermel', [('Baalbek', 'Baalbek'), ('Hermel', 'Hermel')]), ('South Lebanon', [('Sidon', 'Sidon'), ('Jezzine', 'Jezzine'), ('Tyre', 'Tyre')]), ('Nabatieh', [('Nabatieh', 'Nabatieh'), ('Marjeyoun', 'Marjeyoun'), ('Hasbaya', 'Hasbaya'), ('Bint Jbeil', 'Bint Jbeil')])], default='Beirut', max_length=100),
        ),
        migrations.AlterField(
            model_name='driverrequest',
            name='location',
            field=models.CharField(choices=[('Beirut', [('Beirut', 'Beirut')]), ('Mount Lebanon', [('Baabda', 'Baabda'), ('Matn', 'Matn'), ('Chouf', 'Chouf'), ('Aley', 'Aley'), ('Keserwan', 'Keserwan'), ('Jbeil', 'Jbeil')]), ('North Lebanon', [('Tripoli', 'Tripoli'), ('Zgharta', 'Zgharta'), ('Bsharri', 'Bsharri'), ('Batroun', 'Batroun'), ('Koura', 'Koura'), ('Minieh-Danniyeh', 'Minieh-Danniyeh')]), ('Akkar', [('Akkar', 'Akkar')]), ('Beqaa', [('Zahle', 'Zahle'), ('Rashaya', 'Rashaya'), ('West Beqaa', 'West Beqaa')]), ('Baalbek-Hermel', [('Baalbek', 'Baalbek'), ('Hermel', 'Hermel')]), ('South Lebanon', [('Sidon', 'Sidon'), ('Jezzine', 'Jezzine'), ('Tyre', 'Tyre')]), ('Nabatieh', [('Nabatieh', 'Nabatieh'), ('Marjeyoun', 'Marjeyoun'), ('Hasbaya', 'Hasbaya'), ('Bint Jbeil', 'Bint Jbeil')])], max_length=100, verbose_name='Destination'),
        ),
    ]
