# Generated by Django 6.0.1 on 2026-02-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_driver_license_info_driver_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Edit Requested', 'Edit Requested'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', max_length=20),
        ),
    ]
