# Generated by Django 6.0.1 on 2026-02-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_engineer_maintenanceassignment_delete_notification'),
    ]

    operations = [
        # Add indexes for ServiceReport queries
        migrations.AddIndex(
            model_name='servicereport',
            index=models.Index(fields=['engineer', 'status'], name='core_sr_eng_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereport',
            index=models.Index(fields=['status'], name='core_sr_status_idx'),
        ),
        
        # Add indexes for MaintenanceRequest queries
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['status'], name='core_mr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['urgency', 'created_at'], name='core_mr_urg_created_idx'),
        ),
        
        # Add indexes for MaintenanceAssignment queries
        migrations.AddIndex(
            model_name='maintenanceassignment',
            index=models.Index(fields=['engineer', 'date'], name='core_ma_eng_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceassignment',
            index=models.Index(fields=['date'], name='core_ma_date_idx'),
        ),
        
        # Add indexes for DriverRequest queries
        migrations.AddIndex(
            model_name='driverrequest',
            index=models.Index(fields=['status'], name='core_dr_status_idx'),
        ),
    ]
