# Generated by Django 6.0.1 on 2026-02-20 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='driverrequest',
            name='core_dr_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceassignment',
            name='core_ma_eng_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceassignment',
            name='core_ma_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenancerequest',
            name='core_mr_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenancerequest',
            name='core_mr_urg_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicereport',
            name='core_sr_eng_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicereport',
            name='core_sr_status_idx',
        ),
        migrations.AddIndex(
            model_name='driverrequest',
            index=models.Index(fields=['date'], name='core_dr_date_idx'),
        ),
    ]
