# Generated by Django 6.0.1 on 2026-02-20 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_driverrequest_core_dr_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='maintenanceassignment',
            index=models.Index(fields=['engineer', 'date'], name='core_ma_eng_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceassignment',
            index=models.Index(fields=['date'], name='core_ma_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['status'], name='core_mr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['urgency', 'created_at'], name='core_mr_urg_created_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereport',
            index=models.Index(fields=['engineer', 'status'], name='core_sr_eng_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereport',
            index=models.Index(fields=['status'], name='core_sr_status_idx'),
        ),
    ]
