# Generated by Django 6.0.1 on 2026-02-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_maintenanceassignment_core_ma_eng_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Edit Requested', 'Edit Requested'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', max_length=20),
        ),
    ]
