# Generated by Django 6.0.1 on 2026-04-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_driverrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverrequest',
            name='origin',
        ),
    ]
