# Generated by Django 4.2.7 on 2026-01-27 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='tender_docs/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline', models.CharField(blank=True, max_length=255, null=True)),
                ('lots', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('tenderer', models.CharField(blank=True, max_length=255, null=True)),
                ('important_notes', models.TextField(blank=True, null=True)),
                ('quality_certificates', models.TextField(blank=True, null=True)),
                ('raw_summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tender Summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
