# Generated by Django 6.0.1 on 2026-01-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendersummary',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
