# Generated by Django 6.0.1 on 2026-01-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docai', '0002_tendersummary_failure_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendersummary',
            name='bid_security',
            field=models.CharField(blank=True, help_text='Bond amount and format', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tendersummary',
            name='clarification_deadline',
            field=models.CharField(blank=True, help_text='Deadline for asking questions', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tendersummary',
            name='document_checklist',
            field=models.TextField(blank=True, help_text='List of all required submission files', null=True),
        ),
        migrations.AddField(
            model_name='tendersummary',
            name='financial_thresholds',
            field=models.TextField(blank=True, help_text='Minimum annual turnover and financial requirements', null=True),
        ),
        migrations.AddField(
            model_name='tendersummary',
            name='key_experts',
            field=models.TextField(blank=True, help_text='Specific roles and certifications required', null=True),
        ),
        migrations.AddField(
            model_name='tendersummary',
            name='killer_clauses',
            field=models.TextField(blank=True, help_text='Unusual or high-risk clauses', null=True),
        ),
        migrations.AddField(
            model_name='tendersummary',
            name='maintenance_warranty',
            field=models.TextField(blank=True, help_text='Post-delivery obligations and warranty terms', null=True),
        ),
        migrations.AddField(
            model_name='tendersummary',
            name='past_performance',
            field=models.TextField(blank=True, help_text='Similar project requirements', null=True),
        ),
        migrations.AddField(
            model_name='tendersummary',
            name='site_visit',
            field=models.TextField(blank=True, help_text='Mandatory or optional site visits/meetings', null=True),
        ),
        migrations.AddField(
            model_name='tendersummary',
            name='technical_financial_split',
            field=models.CharField(blank=True, help_text='Evaluation weighting (e.g. 60/40)', max_length=255, null=True),
        ),
    ]
