# Generated by Django 6.0.1 on 2026-01-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docai', '0003_tendersummary_bid_security_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendersummary',
            name='currency_code',
            field=models.CharField(blank=True, help_text='Currency code (e.g., USD, EUR, LBP)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tendersummary',
            name='local_presence_required',
            field=models.BooleanField(default=False, help_text='Is a local partner or office mandatory?'),
        ),
    ]
