# Generated by Django 6.0.1 on 2026-02-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docai', '0004_tendersummary_currency_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendersummary',
            name='currency_code',
            field=models.CharField(blank=True, help_text='Currency code (e.g., USD, EUR, LBP)', max_length=100, null=True),
        ),
    ]
