# Generated by Django 6.0.1 on 2026-02-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docai', '0005_alter_tendersummary_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendersummary',
            name='analysis_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tendersummary',
            name='current_step',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
