# Generated by Django 6.0.1 on 2026-02-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docai', '0006_tendersummary_analysis_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendersummary',
            name='is_human_enhanced',
            field=models.BooleanField(default=False, help_text='Has this summary been manually edited by a human?'),
        ),
    ]
