# Generated by Django 6.0.1 on 2026-02-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docai', '0007_tendersummary_is_human_enhanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendersummary',
            name='category',
            field=models.CharField(blank=True, choices=[('medical', 'Medical'), ('lab', 'Lab'), ('agricultural', 'Agricultural'), ('industrial', 'Industrial'), ('educational', 'Educational'), ('research', 'Research'), ('mix', 'Mix')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tendersummary',
            name='continent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tendersummary',
            name='donor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
