"""
Static product catalogue used to populate the Add Product modal dropdowns.
Served directly from memory — no DB query required.
Run `python manage.py seed_product_catalogue` to persist these to the Product table.
"""

CATALOGUE = {
    "IT": [
        # Servers & Computing
        "Server Rack",
        "Tower Server",
        "Blade Server",
        "Desktop Workstation",
        "Laptop",
        "Tablet",
        "All-in-One PC",
        "Mini PC",
        # Networking
        "Network Switch (Managed)",
        "Network Switch (Unmanaged)",
        "Router",
        "Firewall Appliance",
        "Wireless Access Point",
        "Network Attached Storage (NAS)",
        "Load Balancer",
        "VPN Concentrator",
        # Printing & Scanning
        "Laser Printer",
        "Inkjet Printer",
        "Multifunction Printer",
        "Label Printer",
        "Document Scanner",
        "Barcode Scanner",
        "Card Printer",
        # Storage
        "SAN Storage Array",
        "Tape Drive / Tape Library",
        "Backup Appliance",
        "External Hard Drive Array",
        # Security & Surveillance
        "IP Camera",
        "DVR / NVR System",
        "Access Control Panel",
        "Biometric Reader",
        "Video Intercom System",
        # Power
        "UPS (Uninterruptible Power Supply)",
        "Power Distribution Unit (PDU)",
        "Rack-Mount UPS",
        # Display & Peripherals
        "Monitor",
        "Projector",
        "Interactive Whiteboard",
        "Video Conferencing System",
        "KVM Switch",
        # Telecom
        "PABX Phone System",
        "VoIP Phone",
        "IP Intercom",
        "Call Recording System",
    ],

    "Medical": [
        # Diagnostic Imaging
        "MRI Scanner",
        "CT Scanner",
        "Digital X-Ray System",
        "Portable X-Ray Unit",
        "C-Arm Fluoroscopy System",
        "Digital Mammography System",
        "Ultrasound System",
        "PET Scanner",
        "Bone Densitometer (DEXA)",
        "Nuclear Medicine Gamma Camera",
        # Patient Monitoring
        "Patient Monitor (Bedside)",
        "Central Monitoring Station",
        "ECG / EKG Machine",
        "Holter Monitor",
        "Ambulatory Blood Pressure Monitor",
        "Pulse Oximeter",
        "Capnograph",
        # Life Support
        "Mechanical Ventilator",
        "Anesthesia Machine",
        "Defibrillator / AED",
        "Infusion Pump",
        "Syringe Pump",
        "CPAP / BiPAP Machine",
        "Intra-Aortic Balloon Pump",
        "Hemodialysis Machine",
        "Continuous Renal Replacement Therapy (CRRT)",
        # Surgical
        "Surgical Robot",
        "Electrosurgical Unit (ESU)",
        "Laparoscopic Tower",
        "Surgical Light",
        "Operating Table",
        "Harmonic Scalpel",
        "Surgical Microscope",
        # Sterilization
        "Steam Autoclave Sterilizer",
        "UV Sterilizer Cabinet",
        "Ethylene Oxide (ETO) Sterilizer",
        "Dry Heat Oven",
        "Plasma Sterilizer",
        # Ophthalmology
        "Slit Lamp Biomicroscope",
        "Auto Refractometer / Keratometer",
        "Fundus Camera",
        "Non-Contact Tonometer",
        "OCT (Optical Coherence Tomography)",
        "Phacoemulsification System",
        # Dental
        "Dental Chair Unit",
        "Intraoral X-Ray",
        "Panoramic X-Ray (OPG)",
        "Dental Cone Beam CT (CBCT)",
        "Intraoral Scanner",
        "Dental Autoclave",
        "Dental Air Compressor",
        # Rehabilitation & Physiotherapy
        "Physiotherapy Ultrasound Unit",
        "TENS / EMS Unit",
        "Shortwave Diathermy",
        "Laser Therapy Unit",
        "Traction Table",
        "Hydrotherapy Tub",
        # Endoscopy
        "Video Endoscope System",
        "Bronchoscope",
        "Colonoscope",
        "Cystoscope",
        "Endoscopy Reprocessor",
        # Emergency & ICU
        "Cardiac Output Monitor",
        "Hypothermia / Warming Blanket System",
        "Neonatal Incubator",
        "Phototherapy Unit",
        "Transcranial Doppler",
    ],

    "Lab": [
        # Clinical Chemistry
        "Chemistry Analyzer",
        "Electrolyte Analyzer",
        "Blood Gas Analyzer",
        "Lipid Panel Analyzer",
        "Glycated Hemoglobin (HbA1c) Analyzer",
        "Urine Chemistry Analyzer",
        # Hematology
        "Hematology Analyzer (CBC)",
        "Differential Blood Cell Counter",
        "ESR Analyzer",
        "Coagulation Analyzer",
        "Platelet Aggregation Analyzer",
        # Microbiology
        "Automated Blood Culture System",
        "MALDI-TOF Mass Spectrometer",
        "Antibiotic Susceptibility Testing System",
        "Microbiology Incubator",
        "Colony Counter",
        # Immunology & Serology
        "Immunoassay Analyzer (ELISA / CLIA)",
        "ELISA Microplate Reader",
        "ELISA Washer",
        "Flow Cytometer",
        "Immunofluorescence Microscope",
        "Rapid Test Reader",
        # Molecular Biology
        "Real-Time PCR (qPCR) System",
        "Thermal Cycler (PCR)",
        "DNA Sequencer",
        "Gel Electrophoresis System",
        "Nucleic Acid Extractor",
        "Hybridization Oven",
        # Microscopy
        "Optical / Compound Microscope",
        "Phase Contrast Microscope",
        "Fluorescence Microscope",
        "Digital Microscope",
        "Electron Microscope (SEM/TEM)",
        # General Laboratory
        "Refrigerated Centrifuge",
        "Microcentrifuge",
        "UV-Vis Spectrophotometer",
        "Flame Photometer",
        "CO2 Incubator",
        "Dry Block Incubator",
        "Biosafety Cabinet (Class II)",
        "Laminar Flow Hood",
        "Analytical Balance",
        "Precision Balance",
        "Vortex Mixer",
        "Magnetic Stirrer with Hotplate",
        "Water Bath",
        "Freeze Dryer (Lyophilizer)",
        "Ultra-Low Temperature Freezer (-80°C)",
        "Refrigerator (2-8°C)",
        "Autoclave (Lab Grade)",
        # Pathology & Histology
        "Tissue Processor",
        "Microtome",
        "Cryostat",
        "Embedding Center",
        "Slide Stainer",
        "Coverslip Machine",
        # Transfusion Medicine
        "Blood Bank Refrigerator",
        "Platelet Agitator / Incubator",
        "Blood Grouping Analyzer",
        "Blood Irradiator",
        # Urinalysis
        "Urine Analyzer (Chemistry + Microscopy)",
        "Urine Strip Reader",
        # Toxicology / Advanced Analytics
        "Drug of Abuse Analyzer",
        "High-Performance Liquid Chromatograph (HPLC)",
        "Gas Chromatograph (GC)",
        "Atomic Absorption Spectrophotometer (AAS)",
    ],

    "Industrial": [
        # Power Generation
        "Diesel Generator",
        "Gas Generator",
        "Solar Panel System",
        "Industrial UPS",
        "Power Transformer",
        "Automatic Voltage Regulator (AVR)",
        "Changeover Switch / ATS",
        "Solar Inverter",
        # HVAC & Refrigeration
        "Industrial Chiller (Air-Cooled)",
        "Industrial Chiller (Water-Cooled)",
        "Air Handling Unit (AHU)",
        "Fan Coil Unit (FCU)",
        "Industrial Boiler",
        "Cooling Tower",
        "Heat Pump",
        "Industrial Exhaust Fan",
        "Split AC Unit (Industrial)",
        "Precision Air Conditioning (PAC)",
        # Compressed Air & Gas
        "Screw Air Compressor",
        "Piston Air Compressor",
        "Refrigerated Air Dryer",
        "Desiccant Air Dryer",
        "Nitrogen Generator",
        "Medical Air Plant",
        "Oxygen Generator",
        "Vacuum Pump",
        # Material Handling
        "Electric Forklift",
        "Diesel Forklift",
        "Overhead Crane",
        "Jib Crane",
        "Conveyor Belt System",
        "Roller Conveyor",
        "Pallet Jack (Electric)",
        "Scissor Lift",
        "Goods / Freight Elevator",
        "Stacker",
        # Pumps & Fluid Systems
        "Centrifugal Pump",
        "Submersible Pump",
        "Peristaltic Pump",
        "Hydraulic Power Unit",
        "Pressure Vessel",
        "Dosing / Metering Pump",
        # Welding & Fabrication
        "MIG Welder",
        "TIG Welder",
        "Plasma Cutter",
        "Spot Welder",
        "Laser Cutting Machine",
        "Angle Grinder",
        # CNC & Machining
        "CNC Lathe",
        "CNC Milling Machine",
        "CNC Router",
        "EDM Machine",
        "3D Printer (Industrial)",
        "Coordinate Measuring Machine (CMM)",
        # Fire Safety
        "Fire Alarm Control Panel",
        "Sprinkler System",
        "CO2 / FM200 Fire Suppression System",
        "Fire Pump",
        "Gas Detection System",
        "Emergency Lighting System",
        # Water Treatment
        "Reverse Osmosis (RO) System",
        "Water Softener",
        "UV Water Sterilizer",
        "Water Purification System",
        "Wastewater Treatment Plant",
        "Chemical Dosing System",
        # Process Control
        "Industrial PLC System",
        "SCADA System",
        "Variable Frequency Drive (VFD)",
        "Industrial Weighing Scale",
        "Flow Meter",
        "Level Sensor / Transmitter",
    ],

    "Agriculture": [
        # Tractors & Power Equipment
        "Agricultural Tractor (2WD)",
        "Agricultural Tractor (4WD)",
        "Mini Tractor / Power Tiller",
        "Agricultural ATV / Utility Vehicle",
        # Tillage & Soil Preparation
        "Rotary Tiller",
        "Disc Harrow",
        "Moldboard Plow",
        "Subsoiler",
        "Land Leveler / Grader",
        "Ridge Maker",
        # Planting & Seeding
        "Seed Drill",
        "Precision Planter",
        "Broadcast Spreader",
        "Transplanting Machine",
        "Dibbler",
        # Irrigation & Water Management
        "Drip Irrigation System",
        "Center Pivot Irrigator",
        "Sprinkler Irrigation System",
        "Surface Drip Tape",
        "Submersible Water Pump (Agriculture)",
        "Water Tank / Storage",
        "Rain Gun Sprinkler",
        # Crop Protection
        "Tractor-Mounted Sprayer",
        "Knapsack / Backpack Sprayer",
        "Drone Crop Sprayer",
        "Fogger / Misting Machine",
        "Soil Fumigation Machine",
        # Harvesting
        "Combine Harvester",
        "Rice Harvester",
        "Hay Mower",
        "Hay Baler",
        "Silage Harvester / Forage Chopper",
        "Potato Harvester",
        "Vegetable Harvester",
        "Fruit Picking Platform",
        # Post-Harvest & Storage
        "Grain Dryer",
        "Grain Silo",
        "Grain Cleaner / Separator",
        "Rice Huller / Polisher",
        "Cold Storage Unit (Agricultural)",
        "Vacuum Cooler",
        "Sorting & Grading Machine",
        # Soil Testing & Analysis
        "Soil Testing Kit",
        "Portable Soil pH Meter",
        "Portable EC Meter",
        "Soil Moisture Sensor",
        "Weather Station (Agricultural)",
        # Fertilization
        "Fertilizer Spreader",
        "Liquid Fertilizer Injector",
        "Compost Turner",
        "Organic Waste Shredder",
        # Livestock & Poultry
        "Milking Machine",
        "Feed Mixer / TMR Mixer",
        "Animal Scale",
        "Egg Incubator (Poultry)",
        "Poultry Ventilation Fan",
        "Automatic Feeder System",
        # Greenhouse & Controlled Environment
        "Hydroponic / NFT System",
        "Greenhouse Climate Controller",
        "LED Grow Lights",
        "Fogger / Misting Cooling System",
        "Automated Irrigation Controller",
        "CO2 Enrichment System",
    ],
}
