"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY: Secret key from environment variable (never commit this!)
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY: Debug mode from environment (default False for production)
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['medilabengineering.onrender.com', 'www.medilabengineering.onrender.com', '127.0.0.1', 'localhost', '.onrender.com']

if DEBUG:
    ALLOWED_HOSTS = ['*']

# SECURITY: CSRF trusted origins for production
CSRF_TRUSTED_ORIGINS = ['https://medilab-i98o.onrender.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',  # For Cloudflare R2 integration
    'debug_toolbar',
    'core',
    'docai',
    'webpush',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

INTERNAL_IPS = [
    "127.0.0.1",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.user_roles',
                'core.context_processors.notification_counts',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=True,  # Supabase requires SSL
    )
}

# Supabase uses PgBouncer (transaction pooling) which does not support
# server-side cursors. This setting tells Django to use client-side cursors.
DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True


# Caching Configuration (for dashboard stats performance)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Use cached_db session engine — sessions are backed by both cache and DB,
# so they survive server restarts. The session DB write (~496ms) remains,
# but login sessions are fully persistent.
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_ROOT = BASE_DIR / 'staticfiles'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# OpenAI API Settings
OPENAI_API_KEY = os.getenv('OPENAI_API')

# Cloudflare R2 Storage Configuration
# R2 is S3-compatible, so we use AWS S3 settings
AWS_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.getenv('R2_BUCKET_NAME', 'medilab')
AWS_S3_ENDPOINT_URL = os.getenv('R2_ENDPOINT_URL', '')
AWS_S3_REGION_NAME = 'auto'  # Cloudflare R2 uses 'auto' for region
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_FILE_OVERWRITE = True  # Skip HeadObject pre-check; filenames are unique by design
AWS_DEFAULT_ACL = None  # R2 does not support S3-style ACLs
AWS_S3_VERIFY = True
AWS_QUERYSTRING_AUTH = False  # Don't add auth params to URLs
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',  # Cache for 1 day
}

# Use custom domain (public R2 URL) for file URLs
R2_PUBLIC_URL = os.getenv('R2_PUBLIC_URL', '')
if R2_PUBLIC_URL:
    AWS_S3_CUSTOM_DOMAIN = R2_PUBLIC_URL.replace('https://', '').replace('http://', '')
    MEDIA_URL = R2_PUBLIC_URL + '/'
else:
    AWS_S3_CUSTOM_DOMAIN = ''
    MEDIA_URL = '/media/'  # Fallback to prevent crashes, but R2 credentials are required for functionality

# Use R2 for media storage only when credentials are configured; fall back to
# local filesystem storage for development without R2 credentials.
_r2_configured = bool(AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_S3_ENDPOINT_URL)

STORAGES = {
    'default': {
        'BACKEND': (
            'storages.backends.s3boto3.S3Boto3Storage'
            if _r2_configured
            else 'django.core.files.storage.FileSystemStorage'
        ),
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# =============================================================================
# SECURITY SETTINGS
# =============================================================================

# XSS Protection
SECURE_BROWSER_XSS_FILTER = True

# Prevent MIME type sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# Clickjacking protection (stricter than default)
X_FRAME_OPTIONS = 'DENY'

# Session security (only enforce HTTPS cookies in production)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# HTTPS redirect (only in production)
# SECURE_SSL_REDIRECT = not DEBUG

# HSTS (HTTP Strict Transport Security) - be careful, this is cached by browsers
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Web Push Configuration
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": os.getenv('VAPID_PUBLIC_KEY'),
    "VAPID_PRIVATE_KEY": os.getenv('VAPID_PRIVATE_KEY').replace('\\n', '\n') if os.getenv('VAPID_PRIVATE_KEY') else None,
    "VAPID_ADMIN_EMAIL": os.getenv('VAPID_ADMIN_EMAIL')
}
